### ISSUE TITLE
public history modified

### ISSUE THREAD

**Issue by bmcdonnell-ionx** [SiliconLabs/peripheral_examples#11]
Why did you blow away the old repo history? This makes it more difficult to maintain local branches.

**Comment by silabs-austin** [comment]
Due to the way we previously maintained this GitHub repository, we made the decision to wipe the repo history with the most recent re-organization and new internal maintenance procedure. We realize this is not "best practice" and going forward will make every attempt to avoid obliterating the repo history. Sorry for any inconvenience this decision may have caused.
