### ISSUE TITLE
Can not build project

### ISSUE THREAD

**Issue by thanhtungbk61** [SiliconLabs/peripheral_examples#28]
Hi,
After i do follow those steps, i can not build project, so please tell me what i have to do to build the example project.
Thanks you!!

1. In Simplicity Studio:
File -> Import, or
Project -> Import -> MCU Project
2. Navigate to the desired .slsproj file
![Ảnh chụp màn hình (78)](https://user-images.githubusercontent.com/54194621/70149888-9748c900-16db-11ea-9cc6-5d616eef537a.png)

**Comment by hainahouwei** [comment]
I have got the same issue in IAR!
I can open the project by IAR ,but when I make the project  ,it seems  miss many  files.So where can I find the startup_efr32mg21.s file ?
![图片](https://user-images.githubusercontent.com/41433745/71828772-03a15880-30de-11ea-949b-69d7ada64d34.png)

**Comment by silabs-BrianL** [comment]
> Hi,
> After i do follow those steps, i can not build project, so please tell me what i have to do to build the example project.
> Thanks you!!
> 
> 1. In Simplicity Studio:
>    File -> Import, or
>    Project -> Import -> MCU Project
> 2. Navigate to the desired .slsproj file
>    ![Ảnh chụp màn hình (78)](https://user-images.githubusercontent.com/54194621/70149888-9748c900-16db-11ea-9cc6-5d616eef537a.png)

Make sure that you have the latest SDK downloaded and selected whenever you import the project. If you go to Help -> Update Software -> Package Manager -> SDKs, make sure you have the Gecko Platform 2.7.0 installed (at the bottom of the list), and the 32-bit MCU SDK - 5.9.0.0 installed as well. If you do, you should be able to select it when you import the project:

![image](https://user-images.githubusercontent.com/20864432/72094166-6d3a8600-32db-11ea-8972-9aaec41d1bb1.png)

**Comment by silabs-BrianL** [comment]
> I have got the same issue in IAR!
> I can open the project by IAR ,but when I make the project ,it seems miss many files.So where can I find the startup_efr32mg21.s file ?
> ![图片](https://user-images.githubusercontent.com/41433745/71828772-03a15880-30de-11ea-949b-69d7ada64d34.png)

This just looks like an issue where the project is attempting to look for the SDK in a particular location, but it's not located there. To resolve this, you could copy the contents of the SDK into the G:\Peripheral examples for MG21\ directory (so that G:\Peripheral examples for MG21\platform exists, for example). Otherwise, you would need to place the examples in a folder one level deep in your SDK directory. For example, if the SDK is located under G:\SDK, you would place the examples one folder up from there, so the 'series2' folder would exist under G:\SDK\examples\series2.
