### ISSUE TITLE
Pin reset or watchdog reset?

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/peripheral_examples#58]
peripheral_examples/series1/rmu/rmu_wdog_extended/src/main.c
looks like this is not watchdog reset anymore.

**Comment by silabs-dayoung** [comment]
This example uses pin reset instead of the watchdog reset. The main focus of this project is to show the extended reset capability and not the reset source, so this project was renamed to rmu_pin_reset_extended to reflect that. This fix was applied in commit a5c3785ed8d6a35868bc169f07e40e889087fd2e.
